name: Deploy

on:
  workflow_call:
    inputs:
      projectName:
        description: 'Name Of Project'
        default: 'RunnerTest'
        required: true
        type: string
      appPoolName:
        description: 'IIS Application Pool Name'
        default: 'DefaultAppPool'
        required: true
        type: string
      targetLocation:
        description: 'Trarget Location For Application'
        default: 'C:\\Hartree\\Sites\\RunnerTest'
        required: true
        type: string
      assemblyVersion:
        description: 'Assembly Version'
        default: 'RunnerTest'
        required: true
        type: string

jobs:
  deploy_to_dev:
    name: Deploy To Dev
    needs: build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.projectName }} - ${{ inputs.assemblyVersion }}
          path: .\Publish_Artifacts

      - name: Stop App Pool
        run: .\DeploymentScript\StopAppPool.ps1 ${{ inputs.appPoolName }} 

      - name: Publish File To Server
        run: |
          Remove-Item -Recurse "${{ inputs.targetLocation }}"
          Copy-Item -Path .\Publish_Artifacts -Destination "${{ inputs.targetLocation }}" -recurse -Force

      - name: Start App Pool
        run: .\DeploymentScript\StartAppPool.ps1 ${{ inputs.appPoolName }}