name: Get Build Version
author: Parshad Cholera
description: Generate Version Number For Regular Build And Get Release Version Number For Release Tag

inputs:
  branchReference:
    description: 'Relase Tag Referene'
    default: ''
    required: true
    type: string
  buildNumber:
    description: 'Build Number'
    default: ''
    required: false
    type: string

outputs:
  buildVersion:
    description: "Output Version Number"
    value: ${{ steps.buildVersion.outputs.number }}

runs:
  using: "composite"
  steps:
    - name : Get Version Number
      if: startsWith(${{ inputs.branchReference }}, 'refs/tags/v') != true
      run: echo "package_version=0.0.${{ inputs.buildNumber }}" >> $GITHUB_ENV;
      shell: bash

    - name : Get Release Version Number
      if: startsWith(${{ inputs.branchReference }}, 'refs/tags/v')
      run: echo "package_version=${inputs.branchReference:11}" >> $GITHUB_ENV;
      shell: bash

    - name: "Print Version Number"
      run: echo "Version = $package_version"
      shell: bash

    - name: Version Number
      id: buildVersion
      if: startsWith(${{ inputs.branchReference }}, 'refs/tags/v')
      run: echo "::set-output name=number::$package_version";
      shell: bash
