name: Get Build Config
on:
  workflow_call:
    outputs:
      repositoryName:
        description: "Repository Name"
        value: ${{ jobs.buildConfig.outputs.repositoryName }}

      branchType:
        description: "Branch Type"
        value: ${{ jobs.buildConfig.outputs.branchType }}

      buildVersion:
        description: "Output Version Number"
        value: ${{ jobs.buildConfig.outputs.version }}

env:
  GITHUB_REF: github.ref

jobs:
  buildConfig:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.buildVersion.outputs.number }}
      branchType: ${{ steps.branchName.outputs.name }}
      repositoryName: ${{ steps.repositoryName.outputs.name }}

    steps:
      - uses: jungwinter/split@v2
        id: repositoryNameSplit
        with:
          msg: ${{ github.repository }}
          separator: '/'

      - uses: jungwinter/split@v2
        id: branchNameSplit
        with:
          msg: ${{ github.ref_name }}
          separator: '/'

      - name: Generate Build Number
        id: buildNumber
        if: startsWith(github.ref, 'refs/tags/v') != true && github.ref_name == 'main'
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}

      - name : Get Version Number
        if: startsWith(github.ref, 'refs/tags/v') != true && github.ref_name == 'main'
        run: echo "package_version=0.1.${{ steps.buildNumber.outputs.build_number }}" >> $GITHUB_ENV;
        shell: bash

      - name : Get Release Version Number
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "package_version=${GITHUB_REF:11}" >> $GITHUB_ENV;
        shell: bash

      - name: Repository Name
        id: repositoryName
        run: echo "name=${{ steps.repositoryNameSplit.outputs._1 }}" >> $GITHUB_OUTPUT;
        shell: bash

      - name: Branch Type
        id: branchName
        run: echo "name=${{ steps.branchNameSplit.outputs._0 }}" >> $GITHUB_OUTPUT;
        shell: bash

      - name: Version Number
        id: buildVersion
        run: echo "number=$package_version" >> $GITHUB_OUTPUT;
        shell: bash
