name: Get Build Version
on:
  workflow_call:
    outputs:
      buildVersion:
        description: "Output Version Number"
        value: ${{ jobs.buildVersion.outputs.version }}

env:
  GITHUB_REF: github.ref

jobs:
  buildVersion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.buildVersion.outputs.number }}

    steps:
      - name: Generate Build Number
        id: buildNumber
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name : Get Version Number
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: echo "package_version=0.0.${{ steps.buildNumber.outputs.build_number }}" >> $GITHUB_ENV;
        shell: bash

      - name : Get Release Version Number
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "package_version=${GITHUB_REF:11}" >> $GITHUB_ENV;
        shell: bash

      - name: "Print Version Number"
        run: echo "Version = $package_version"
        shell: bash

      - name: Version Number
        id: buildVersion
        run: echo "::set-output name=number::$package_version";
        shell: bash
