name: Deploy Build To Server

on:
  workflow_dispatch:
    inputs:
      appPoolName:
        description: 'IIS Application Pool Name'
        default: 'DefaultAppPool'
        required: true
        type: choice
        options:
        - DefaultAppPool
      targetLocation:
        description: 'Trarget Location For Application'
        default: 'C:\\Hartree\\Sites\\RunnerTest'
        required: true
        type: string
      assemblyVersion:
        description: 'Assembly Version'
        default: ''
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      appPoolName: ${{ github.event.inputs.appPoolName }}
      targetLocation: ${{ github.event.inputs.targetLocation }}
      assemblyVersion: ${{ github.event.inputs.assemblyVersion }}