name: Deploy_Manual

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Name Of Project'
        default: 'RunnerTest'
        required: true
        type: string
      appPoolName:
        description: 'IIS Application Pool Name'
        default: 'DefaultAppPool'
        required: true
        type: choice
        options:
        - DefaultAppPool
      targetLocation:
        description: 'Trarget Location For Application'
        default: 'C:\\Hartree\\Sites\\RunnerTest'
        required: true
        type: string
      assemblyVersion:
        description: 'Assembly Version'
        default: ''
        required: true
        type: string

env:
  sourceLocation: ".\\Publish_Artifacts"

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      # - name: Download Artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: ${{ github.event.inputs.projectName }} - ${{ github.event.inputs.assemblyVersion }}
      #     path: ${{ env.sourceLocation }}

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: Build
          workflow_conclusion: success
          #name: ${{ github.event.inputs.projectName }} - ${{ github.event.inputs.assemblyVersion }}
          path: ${{ env.sourceLocation }}

      - name: Stop App Pool
        run: .\DeploymentScript\StopAppPool.ps1 ${{ github.event.inputs.appPoolName }} 

      - name: Publish File To Server
        run: |
          if (test-path "${{ github.event.inputs.targetLocation }}")
          {
            Remove-Item -Recurse "${{ github.event.inputs.targetLocation }}"
          }
          Copy-Item -Path ${{ env.sourceLocation }} -Destination "${{ github.event.inputs.targetLocation }}" -recurse -Force

      - name: Start App Pool
        run: .\DeploymentScript\StartAppPool.ps1 ${{ github.event.inputs.appPoolName }}
