name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        source-url: https://nuget.pkg.github.com/pcholera/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Set VERSION variable
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ steps.buildnumber.outputs.build_number }}.0.0 --no-build --output .

    - name: Push
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.github_token}}
      #run: dotnet nuget push RunnerTest.${{ steps.buildnumber.outputs.build_number }}.0.0.nupkg --source https://nuget.pkg.github.com/pcholera/index.json --api-key ${{secrets.github_token}}
