name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Set VERSION variable
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build RunnerTestProject/RunnerTestProject.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test RunnerTestProject/RunnerTestProject.csproj --configuration Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack RunnerTest/RunnerTest.csproj --configuration Release /p:Version=0.0.${{ steps.buildnumber.outputs.build_number }} --no-build --output .

    - name: Push
      run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
