name: Merge Release Changes To Main

on:
  pull_request:
    types:
      - closed
    branches:    
      - 'release/**'
  
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # - name: Merge Release Changes To Main
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     target_branch: main
      #     github_token: ${{ github.token }}

      - name: Merge Release Changes To Main
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'main'
          development_branch: ${{ github.ref_name }}
          allow_ff: false
          allow_forks: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
