name: Merge Release Changes To Main

on:
  pull_request:
    types:
      - closed
    branches:    
      - 'release/**'
  
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # - name: Merge Release Changes To Main
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     target_branch: main
      #     github_token: ${{ github.token }}

      - name: Merge Release Changes To Main
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git pull
          git checkout "$GITHUB_HEAD_REF"
          git status
          git checkout main
          git merge "$GITHUB_HEAD_REF" --no-edit
          git push
          git status