name: Build

on: 
  push: 
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  buildConfig:
    name: Get Build Config
    uses: ./.github/workflows/BuildConfig.yml

  build:
    needs: buildConfig

    env:
      projectName: ${{ needs.buildConfig.outputs.repositoryName }}
      projectPath: ${{ needs.buildConfig.outputs.repositoryName }}/${{ needs.buildConfig.outputs.repositoryName }}.csproj

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Print Repo Name"
      run: echo "Repo Name = ${{ needs.buildConfig.outputs.repositoryName }}"

    - name: "Print Branch Type"
      run: echo "Branch Type = ${{ needs.buildConfig.outputs.branchType }}"

    - name: "Print Version Number"
      run: echo "Version = ${{ needs.buildConfig.outputs.buildVersion }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Ensure GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/pcholera/index.json -n github -u ${{ github.actor }}  -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Test
      run: ForEach ($testProjectFile in (Get-ChildItem -Recurse |  Where-Object { $_.Name -like '*TestProject.csproj' })) { dotnet test $testProjectFile.FullName  --filter Category!=Integration --configuration Release }

    - name: Pack
      if: needs.buildConfig.outputs.branchType == 'develop' || startsWith(github.ref, 'refs/tags/v')
      run: dotnet pack ${{ env.projectPath }} --configuration Release /p:Version=${{ needs.buildConfig.outputs.buildVersion }} --no-build --output .

    - name: Push
      if: needs.buildConfig.outputs.branchType == 'develop' || startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate --source github

    - name: Cleanup Github Nuget Source
      if: always()
      continue-on-error: true
      run: dotnet nuget remove source github

  auto_merge_release_to_main:
    needs: [build, buildConfig]
    if: ${{ needs.buildConfig.outputs.branchType }} == 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}
          label_name: 'automerge'
